---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: fm-init-
spec:
  template:
    spec:
      containers:
        - name: fm-init
          image: docker.io/ldonleycb/fm-initializer:7
          env:
            - name: APP_NAME
              value: "REPLACE_APP_NAME"
            - name: CD_PROJECT
              value: "REPLACE_CD_PROJECT"
            - name: EMAIL
              value: "REPLACE_EMAIL"
          envFrom:
            - secretRef:
                name: cd-sa-creds
            - secretRef:
                name: fm-bot
      restartPolicy: OnFailure
  backoffLimit: 4
