---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: fm-init-
spec:
  template:
    spec:
      containers:
        - name: fm-init
          image: docker.io/ldonleycb/fm-initializer:2
          env:
            - name: USER_TOKEN
              value: "REPLACE_USER_TOKEN"
            - name: APP_NAME
              value: "REPLACE_APP_NAME"
      restartPolicy: OnFailure
  backoffLimit: 4
