---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: fm-init-
spec:
  template:
    spec:
      containers:
        - name: fm-init
          image: docker.io/ldonleycb/fm-initializer:4
          env:
            - name: USER_TOKEN
              value: "REPLACE_USER_TOKEN"
            - name: APP_NAME
              value: "REPLACE_APP_NAME"
            - name: CD_PROJECT
              value: "REPLACE_CD_PROJECT"
          envFrom:
            - secretRef:
                name: cd-sa-creds
      restartPolicy: OnFailure
  backoffLimit: 4
